config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scheduler.urls')),
]

scheduler/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
  path('user/<int:pk>/task/<str:day>/', views.task_scheduler_view, name='user_home'),
  path('', views.sign_in, name='login'),
  path('register/', views.sign_up, name="register"),
  path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
  path('create_task/', views.CreateTaskView.as_view(), name='create_task'),
  path('update_task/', views.UpdateTaskView.as_view(), name='update_task'),
  path('delete_task/', views.DeleteTaskView.as_view(), name='delete_task'),
]

scheduler/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    task_name = models.CharField(max_length=100)
    start_time = models.TimeField()
    end_time = models.TimeField()
    day = models.CharField(max_length=10)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

scheduler/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Task


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control',
                                             'placeholder': 'Email'}),
        }

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['password1'] = forms.CharField(widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password'}), label='Password')
        self.fields['password2'] = forms.CharField(widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Retype password'}), label='Confirm password')


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Password'}))


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name', 'start_time', 'end_time', 'day']

        widgets = {
            'task_name': forms.TextInput(attrs={'class': 'form-control form-control-sm',
                                                'placeholder': 'task name'}),
            'start_time': forms.TimeInput(attrs={'class': 'form-control form-control-sm',
                                                 'type': 'time', 'placeholder': 'start'}),
            'end_time': forms.TimeInput(attrs={'class': 'form-control form-control-sm',
                                               'type': 'time'}),
            'day': forms.HiddenInput(),
        }

scheduler/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View

from .forms import UserRegistrationForm, UserLoginForm, TaskForm
from .models import Task


# Create your views here.
def sign_up(request):
    form = UserRegistrationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('login')
    context = {
        'form': form
    }
    return render(request, 'registration/register.html', context=context)


def sign_in(request):
    form = UserLoginForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('user_home', pk=user.id, day='monday')
            else:
                messages.error(request, 'Username or password is incorrect')
    context = {
        'form': form
    }
    return render(request, 'registration/login.html', context=context)


def task_scheduler_view(request, pk, day):
    tasks = Task.objects.filter(user_id=pk, day=day)
    task_form = TaskForm(request.POST or None,
                         initial={'user': get_object_or_404(User, id=pk), 'day': day})

    context = {'tasks': tasks, 'task_form': task_form}
    return render(request, 'scheduler/task_scheduler.html', context=context)


class CreateTaskView(View):
    def get(self, request):
        task_name = request.GET.get('task_name', None)
        start_time = request.GET.get('start_time', None)
        end_time = request.GET.get('end_time', None)
        day = request.GET.get('day', None)
        user = self.request.user

        obj = Task.objects.create(
            user=user,
            day=day,
            task_name=task_name,
            start_time=start_time,
            end_time=end_time,
        )

        task = {'id': obj.id, 'task_name': obj.task_name, 'start_time': obj.start_time, 'end_time': obj.end_time}

        data = {'task': task}
        return JsonResponse(data)


class UpdateTaskView(View):
    def get(self, request):
        task_id = request.GET.get('task_id', None)
        task_name = request.GET.get('task_name', None)
        start_time = request.GET.get('start_time', None)
        end_time = request.GET.get('end_time', None)
        # day = request.GET.get('day', None)
        # user = self.request.user

        obj = Task.objects.get(id=task_id)
        obj.task_name = task_name
        obj.start_time = start_time
        obj.end_time = end_time
        obj.save()

        task = {'id': obj.id, 'task_name': obj.task_name, 'start_time': obj.start_time, 'end_time': obj.end_time}
        data = {'task': task}
        return JsonResponse(data)


class DeleteTaskView(View):
    def get(self, request):
        task_id = request.GET.get('task_id', None)
        Task.objects.get(id=task_id).delete()
        data = {'deleted': True}
        return JsonResponse(data)

scheduler/templates/alert_msg.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} m-0 rounded-0" role="alert">
            {{message}}
        </div>
    {% endfor %}
{% endif %}

scheduler/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly Task Scheduler</title>
    <!-- Font Awsome, Bootstrap, Custom CSS -->
    <link rel="stylesheet" href="{% static 'scheduler/bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'scheduler/font awsome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'scheduler/custom/style/style.css' %}">
    <link rel="stylesheet" href="{% static 'scheduler/custom/style/tooltip-style.css' %}">

    {% block custom_style %}
    {% endblock custom_style %}
</head>
<body>

    {% block content %}
    {% endblock content %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- the slim build of jQuery excludes the ajax and effects modules -->
    <script src="{% static 'scheduler/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'scheduler/popper.min.js' %}"></script>
    <script src="{% static 'scheduler/bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"></script>

    {% block custom_script %}
    {% endblock custom_script %}
</body>
</html>

scheduler/templates/scheduler/task_scheduler.html
{% extends 'base.html' %}

{% load static %}

{% load custom_tags %}

{% block custom_style %}
    <link rel="stylesheet" href="{% static 'scheduler/custom/style/menu_slider.css' %}">
{% endblock custom_style %}


{% block content %}

<div class="container my-5 p-1 bg-white">
    <h2 class="text-center py-3" id="title">Weekly Schedule</h2>
    
    <ul class="nav nav-tabs invisible" id="slider">
        <li class="nav-item"><a class="nav-link active" id="monday-tab" href="{% url 'user_home' user.id 'monday' %}">Monday</a></li>
        <li class="nav-item"><a class="nav-link" id="tuesday-tab" href="{% url 'user_home' user.id 'tuesday' %}">Tuesday</a></li>
        <li class="nav-item"><a class="nav-link" id="wednesday-tab" href="{% url 'user_home' user.id 'wednesday' %}">Wednesday</a></li>
        <li class="nav-item"><a class="nav-link" id="thursday-tab" href="{% url 'user_home' user.id 'thursday' %}">Thursday</a></li>
        <li class="nav-item"><a class="nav-link" id="friday-tab" href="{% url 'user_home' user.id 'friday' %}">Friday</a></li>
        <li class="nav-item"><a class="nav-link" id="saturday-tab" href="{% url 'user_home' user.id 'saturday' %}">Saturday</a></li>
        <li class="nav-item"><a class="nav-link" id="sunday-tab" href="{% url 'user_home' user.id 'sunday' %}">Sunday</a></li>
    </ul>
    <div class="slider mt-3">
        <a id="slideLeft" href="#">&laquo;</a>
        <a id="slideRight" class="float-right" href="#">&raquo;</a>
    </div>

    <div class="d-flex justify-content-between my-4"">
        <h4>{{user}}</h4>
        <a href="{% url 'logout' %}">Logout</a>
    </div>

    <div class="tab-content mt-4">
        <div class="tab-pane fade show active">
            <table id="taskTable" class="table">
                <thead>
                    <tr>
                        <th class="th-lg">Task</th>
                        <th>Start Time</th>
                        <th>End Time</th>
                        <th class="th-sm"></th>
                        <th class="th-sm"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr id="task-{{task.id}}">
                        <td id="task_name" class="taskData">{{task.task_name}}</td>
                        <td id="start_time" class="taskData">{{task.start_time}}</td>
                        <td id="end_time" class="taskData">{{task.end_time}}</td>
                        <td>
                            <a href="#" id="edit" onClick="editTask({{task.id}})" data-toggle="modal" data-target="#myModal">
                                <i class="fas fa-pencil-alt"></i>
                                <span class="tooltiptext">Edit Task</span>
                            </a>
                        </td>
                        <td>
                            <a href="#" id="delete" onClick="deleteTask({{task.id}})">
                                <i class="fas fa-trash-alt"></i>
                                <span class="tooltiptext">Delete Task</span>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="row form-row mt-4">
                <div class="col">
                    <button type='button' class="btn btn-outline-success rounded-0 add-form-row" onClick="addTask()" data-toggle="modal" data-target="#myModal">
                        <span class="fas fa-plus fa-sm"></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

 <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title"></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="alert"></div>
        <form action="" novalidate>
        <div class="modal-body">
            <input type="hidden" name="task_id"  id="id_task_id">
            {{task_form.day}}
            {{task_form.task_name}}
            <div class="d-flex justify-content-between mt-3 mb-5">
                {{task_form.start_time}}
                <span class="mx-2"> to </span> 
                {{task_form.end_time}}
            </div>
            <small id="form-msg" class="text-muted"></small>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-outline-success rounded-0" >Save changes</button>
            <button type="button" class="btn btn-outline-secondary rounded-0" data-dismiss="modal">Close</button>
        </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

{% block custom_script %}
    <script src="{% static 'scheduler/custom/script/menu_slider.js' %}"></script>
    <script src="{% static 'scheduler/custom/script/active_menu.js' %}"></script>

    <script>
        // Create / Update Django Ajax Call
        $("form").submit(function() {
            var taskId = $('input[name="task_id"]').val().trim();
            var dayInput = $('input[name="day"]').val().trim();
            var taskNameInput = $('input[name="task_name"]').val().trim();
            var startTimeInput = $('input[name="start_time"]').val().trim();
            var endTimeInput = $('input[name="end_time"]').val().trim();

            let modalAlert = document.querySelector('.modal .alert');
            if (taskNameInput && startTimeInput && endTimeInput) {
                if(this.id == 'create-task-form'){
                        path = '{% url "create_task" %}';
                        successAction = appendToTaskTable;
                        successMsg = 'New task added.';
                }
                else if(this.id == 'edit-task-form'){
                        path = '{% url "update_task" %}';
                        successAction = updateToTaskTable;
                        successMsg = 'Task edited.';
                }

                // Create / Update Ajax Call
                $.ajax({
                    url: path,
                    data: {
                        'task_id': taskId,
                        'task_name': taskNameInput,
                        'start_time': startTimeInput,
                        'end_time': endTimeInput, 
                        'day': dayInput,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.task) {
                            successAction(data.task);
                            modalAlert.className = "alert alert-success";
                            modalAlert.innerHTML = successMsg;
                            modalAlert.style.display = 'block';
                        }
                    }
                });
                if(this.id == 'create-task-form') $("form").trigger("reset");  
            }        
            else {
                modalAlert.className = "alert alert-danger";
                modalAlert.innerHTML = "Please fill all fields.";
                modalAlert.style.display = 'block';
            }   
            return false;
        });

        function appendToTaskTable(task) {
            startTime = to12HrFormat(task.start_time);
            endTime = to12HrFormat(task.end_time);
            $("#taskTable > tbody:last-child").append(`
                <tr id="task-${task.id}">
                    <td id="task_name">${task.task_name}</td>
                    <td id="start_time">${startTime}</td>
                    <td id="end_time">${endTime}</td>
                    <td>
                        <a href="#" id="edit" onClick="editTask(${task.id})" data-toggle="modal" data-target="#myModal">
                            <i class="fas fa-pencil-alt"></i>
                            <span class="tooltiptext">Edit Task</span>
                        </a>
                    </td>
                    <td>
                        <a href="#" id="delete" onClick="deleteTask(${task.id})">
                            <i class="fas fa-trash-alt"></i>
                            <span class="tooltiptext">Delete Task</span>
                        </a>
                    </td>    
                </tr>
            `);
        }

        function updateToTaskTable(task){
            startTime = to12HrFormat(task.start_time);
            endTime = to12HrFormat(task.end_time);
            let targetTableRow = document.querySelector("#taskTable #task-" + task.id);
            targetTableRow.querySelector('#task_name').innerHTML = task.task_name;
            targetTableRow.querySelector('#start_time').innerHTML = startTime;
            targetTableRow.querySelector('#end_time').innerHTML = endTime;
        }

        function to12HrFormat(time24) {
            [hrs, min] = time24.split(":");
            if (hrs < 12) {
                hrs = Number(hrs);
                if (hrs == 0){
                    hrs = String(12);
                }
                format = "a.m.";
            }
            else if (hrs >= 12) {
                hrs = Number(hrs) - 12;
                if (hrs == 0){
                    hrs = String(12);
                }
                format="p.m.";
            }
            newTime = hrs + ":" + min + " " + format;
            return newTime;
        }

        function to24HrFormat(time12) {
            [time, format] = time12.split(' ');
            if (time.includes(':')){
                [hrs, min] = time.split(':');
            }
            else {
                [hrs, min] = [time, 0];
            }
            
            let now = new Date();
            if(format == "p.m." && hrs<12) hrs = Number(hrs) + 12;
            if(format == "a.m." && hrs==12) hrs = "0";
            time = [hrs, min];
            let date = new Date(now.getFullYear(), now.getMonth(), now.getDate(), ...time);
            newHr = date.getHours();
            newMin = date.getMinutes();
            if (String(newHr).length==1) newHr = '0' + newHr;
            if (String(newMin).length==1) newMin = '0' + newMin;
            newTime = newHr + ':' + newMin;
            return newTime;
		}

        function addTask() {
            $("form").trigger("reset");
            let formElm = document.querySelector('form');
            formElm.id = 'create-task-form';
            document.querySelector(".modal-title").innerHTML = 'Create Task';
            document.querySelector("#form-msg").innerHTML = 'All fields are required.'; 
            document.querySelector('.modal .alert').style.display = 'none';
        }

        function editTask(taskId) {
            let formElm = document.querySelector('form');
            formElm.id = 'edit-task-form';
            document.querySelector('.modal-title').innerHTML = 'Edit Task';
            document.querySelector("#form-msg").innerHTML = 'Save and close when you are done.'; 
            document.querySelector('.modal .alert').style.display = 'none';

            if (taskId) {
                tr_id = "#task-" + taskId;
                taskName = $(tr_id).find("#task_name").text();
                startTime = to24HrFormat($(tr_id).find("#start_time").text());
                endTime = to24HrFormat($(tr_id).find("#end_time").text());
                $('#id_task_id').val(taskId);
                $('#id_task_name').val(taskName);
                $('#id_start_time').val(startTime);
                $('#id_end_time').val(endTime);
            }
        }

        // Delete Django Ajax Call
        function deleteTask(taskId) {
            $.ajax({
                url: '{% url "delete_task" %}',
                data: {
                    'task_id': taskId,
                },
                dataType: 'json',
                success: function (data) {
                    if (data.deleted) {
                        $("#taskTable #task-" + taskId).remove();
                    }
                }
            });
        }
    </script>

{% endblock custom_script %}